--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VectorNetworkProject/TheMix
branches:
- master
- develop
projects:
  TheMix:
    path: ""
    libs:
      - src: fuyutsuki/libform/libform
        version: 0.4.0
      - src: InkoHX/LeveLibrary
        version: 0.0.1
...
