language: php
php:
  - 7.2
sudo: false
dist: trusty

before_script:
- echo | pecl install channel://pecl.php.net/yaml-2.0.2
- git clone https://github.com/krakjoe/pthreads.git
- cd pthreads
- git checkout d32079fb4a88e6e008104d36dbbf0c2dd7deb403
- phpize
- ./configure
- make
- make install
- cd ..
- echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- mkdir "$TRAVIS_BUILD_DIR"/../PocketMine && cd "$TRAVIS_BUILD_DIR"/../PocketMine
- wget -O PocketMine-MP.phar "${1:-"https://github.com/pmmp/PocketMine-MP/releases/download/3.3.2/PocketMine-MP.phar"}"
- mkdir plugins && mkdir unstaged
- wget -O plugins/DevTools.phar https://github.com/pmmp/PocketMine-DevTools/releases/download/v1.13.0/DevTools_v1.13.0.phar
- wget -O plugins/libform.phar https://poggit.pmmp.io/r/45472/libform.phar

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/TheMix.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - TheMix TheMix ; else true ; fi"
- wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - TheMix TheMix
- cd "$TRAVIS_BUILD_DIR"/../PocketMine/

notifications:
  email: false