name: TheMix
main: VectorNetworkProject\TheMix\TheMix
api: 3.0.0
softdepend:
- ScoreboardsPE

description: "Original game of VectorNetwork"
website: "https://vector-network.tk"
version: 0.0.2
authors:
- InkoHX
- MazaiCrafty
- yuko fuyutsuki
- DusKong
- UramnOIL

permissions:
  the.mix.command.ping:
    default: true
  the.mix.command.tps:
    default: true